package com.eyther.lumbridge.domain.mapper.currencyexchange

import com.eyther.lumbridge.data.model.currencyexchange.remote.CurrencyRatesRemote
import com.eyther.lumbridge.domain.model.currencyexchange.CurrencyRates
import java.util.Currency

fun CurrencyRatesRemote.toDomain(): CurrencyRates {
    val ratesMap = mutableMapOf<Currency, Double>()

    rates?.AED?.let { rate -> ratesMap.put(Currency.getInstance("AED"), rate) }
    rates?.AFN?.let { rate -> ratesMap.put(Currency.getInstance("AFN"), rate) }
    rates?.ALL?.let { rate -> ratesMap.put(Currency.getInstance("ALL"), rate) }
    rates?.AMD?.let { rate -> ratesMap.put(Currency.getInstance("AMD"), rate) }
    rates?.ANG?.let { rate -> ratesMap.put(Currency.getInstance("ANG"), rate) }
    rates?.AOA?.let { rate -> ratesMap.put(Currency.getInstance("AOA"), rate) }
    rates?.ARS?.let { rate -> ratesMap.put(Currency.getInstance("ARS"), rate) }
    rates?.AUD?.let { rate -> ratesMap.put(Currency.getInstance("AUD"), rate) }
    rates?.AWG?.let { rate -> ratesMap.put(Currency.getInstance("AWG"), rate) }
    rates?.AZN?.let { rate -> ratesMap.put(Currency.getInstance("AZN"), rate) }
    rates?.BAM?.let { rate -> ratesMap.put(Currency.getInstance("BAM"), rate) }
    rates?.BBD?.let { rate -> ratesMap.put(Currency.getInstance("BBD"), rate) }
    rates?.BDT?.let { rate -> ratesMap.put(Currency.getInstance("BDT"), rate) }
    rates?.BGN?.let { rate -> ratesMap.put(Currency.getInstance("BGN"), rate) }
    rates?.BHD?.let { rate -> ratesMap.put(Currency.getInstance("BHD"), rate) }
    rates?.BIF?.let { rate -> ratesMap.put(Currency.getInstance("BIF"), rate) }
    rates?.BMD?.let { rate -> ratesMap.put(Currency.getInstance("BMD"), rate) }
    rates?.BND?.let { rate -> ratesMap.put(Currency.getInstance("BND"), rate) }
    rates?.BOB?.let { rate -> ratesMap.put(Currency.getInstance("BOB"), rate) }
    rates?.BRL?.let { rate -> ratesMap.put(Currency.getInstance("BRL"), rate) }
    rates?.BSD?.let { rate -> ratesMap.put(Currency.getInstance("BSD"), rate) }
    rates?.BTN?.let { rate -> ratesMap.put(Currency.getInstance("BTN"), rate) }
    rates?.BWP?.let { rate -> ratesMap.put(Currency.getInstance("BWP"), rate) }
    rates?.BYN?.let { rate -> ratesMap.put(Currency.getInstance("BYN"), rate) }
    rates?.BZD?.let { rate -> ratesMap.put(Currency.getInstance("BZD"), rate) }
    rates?.CAD?.let { rate -> ratesMap.put(Currency.getInstance("CAD"), rate) }
    rates?.CDF?.let { rate -> ratesMap.put(Currency.getInstance("CDF"), rate) }
    rates?.CHF?.let { rate -> ratesMap.put(Currency.getInstance("CHF"), rate) }
    rates?.CLP?.let { rate -> ratesMap.put(Currency.getInstance("CLP"), rate) }
    rates?.CNY?.let { rate -> ratesMap.put(Currency.getInstance("CNY"), rate) }
    rates?.COP?.let { rate -> ratesMap.put(Currency.getInstance("COP"), rate) }
    rates?.CRC?.let { rate -> ratesMap.put(Currency.getInstance("CRC"), rate) }
    rates?.CUP?.let { rate -> ratesMap.put(Currency.getInstance("CUP"), rate) }
    rates?.CVE?.let { rate -> ratesMap.put(Currency.getInstance("CVE"), rate) }
    rates?.CZK?.let { rate -> ratesMap.put(Currency.getInstance("CZK"), rate) }
    rates?.DJF?.let { rate -> ratesMap.put(Currency.getInstance("DJF"), rate) }
    rates?.DKK?.let { rate -> ratesMap.put(Currency.getInstance("DKK"), rate) }
    rates?.DOP?.let { rate -> ratesMap.put(Currency.getInstance("DOP"), rate) }
    rates?.DZD?.let { rate -> ratesMap.put(Currency.getInstance("DZD"), rate) }
    rates?.EGP?.let { rate -> ratesMap.put(Currency.getInstance("EGP"), rate) }
    rates?.ERN?.let { rate -> ratesMap.put(Currency.getInstance("ERN"), rate) }
    rates?.ETB?.let { rate -> ratesMap.put(Currency.getInstance("ETB"), rate) }
    rates?.EUR?.let { rate -> ratesMap.put(Currency.getInstance("EUR"), rate) }
    rates?.FJD?.let { rate -> ratesMap.put(Currency.getInstance("FJD"), rate) }
    rates?.FKP?.let { rate -> ratesMap.put(Currency.getInstance("FKP"), rate) }
    rates?.FOK?.let { rate -> ratesMap.put(Currency.getInstance("FOK"), rate) }
    rates?.GBP?.let { rate -> ratesMap.put(Currency.getInstance("GBP"), rate) }
    rates?.GEL?.let { rate -> ratesMap.put(Currency.getInstance("GEL"), rate) }
    rates?.GGP?.let { rate -> ratesMap.put(Currency.getInstance("GGP"), rate) }
    rates?.GHS?.let { rate -> ratesMap.put(Currency.getInstance("GHS"), rate) }
    rates?.GIP?.let { rate -> ratesMap.put(Currency.getInstance("GIP"), rate) }
    rates?.GMD?.let { rate -> ratesMap.put(Currency.getInstance("GMD"), rate) }
    rates?.GNF?.let { rate -> ratesMap.put(Currency.getInstance("GNF"), rate) }
    rates?.GTQ?.let { rate -> ratesMap.put(Currency.getInstance("GTQ"), rate) }
    rates?.GYD?.let { rate -> ratesMap.put(Currency.getInstance("GYD"), rate) }
    rates?.HKD?.let { rate -> ratesMap.put(Currency.getInstance("HKD"), rate) }
    rates?.HNL?.let { rate -> ratesMap.put(Currency.getInstance("HNL"), rate) }
    rates?.HRK?.let { rate -> ratesMap.put(Currency.getInstance("HRK"), rate) }
    rates?.HTG?.let { rate -> ratesMap.put(Currency.getInstance("HTG"), rate) }
    rates?.HUF?.let { rate -> ratesMap.put(Currency.getInstance("HUF"), rate) }
    rates?.IDR?.let { rate -> ratesMap.put(Currency.getInstance("IDR"), rate) }
    rates?.ILS?.let { rate -> ratesMap.put(Currency.getInstance("ILS"), rate) }
    rates?.IMP?.let { rate -> ratesMap.put(Currency.getInstance("IMP"), rate) }
    rates?.INR?.let { rate -> ratesMap.put(Currency.getInstance("INR"), rate) }
    rates?.IQD?.let { rate -> ratesMap.put(Currency.getInstance("IQD"), rate) }
    rates?.IRR?.let { rate -> ratesMap.put(Currency.getInstance("IRR"), rate) }
    rates?.ISK?.let { rate -> ratesMap.put(Currency.getInstance("ISK"), rate) }
    rates?.JEP?.let { rate -> ratesMap.put(Currency.getInstance("JEP"), rate) }
    rates?.JMD?.let { rate -> ratesMap.put(Currency.getInstance("JMD"), rate) }
    rates?.JOD?.let { rate -> ratesMap.put(Currency.getInstance("JOD"), rate) }
    rates?.JPY?.let { rate -> ratesMap.put(Currency.getInstance("JPY"), rate) }
    rates?.KES?.let { rate -> ratesMap.put(Currency.getInstance("KES"), rate) }
    rates?.KGS?.let { rate -> ratesMap.put(Currency.getInstance("KGS"), rate) }
    rates?.KHR?.let { rate -> ratesMap.put(Currency.getInstance("KHR"), rate) }
    rates?.KID?.let { rate -> ratesMap.put(Currency.getInstance("KID"), rate) }
    rates?.KMF?.let { rate -> ratesMap.put(Currency.getInstance("KMF"), rate) }
    rates?.KRW?.let { rate -> ratesMap.put(Currency.getInstance("KRW"), rate) }
    rates?.KWD?.let { rate -> ratesMap.put(Currency.getInstance("KWD"), rate) }
    rates?.KYD?.let { rate -> ratesMap.put(Currency.getInstance("KYD"), rate) }
    rates?.KZT?.let { rate -> ratesMap.put(Currency.getInstance("KZT"), rate) }
    rates?.LAK?.let { rate -> ratesMap.put(Currency.getInstance("LAK"), rate) }
    rates?.LBP?.let { rate -> ratesMap.put(Currency.getInstance("LBP"), rate) }
    rates?.LKR?.let { rate -> ratesMap.put(Currency.getInstance("LKR"), rate) }
    rates?.LRD?.let { rate -> ratesMap.put(Currency.getInstance("LRD"), rate) }
    rates?.LSL?.let { rate -> ratesMap.put(Currency.getInstance("LSL"), rate) }
    rates?.LYD?.let { rate -> ratesMap.put(Currency.getInstance("LYD"), rate) }
    rates?.MAD?.let { rate -> ratesMap.put(Currency.getInstance("MAD"), rate) }
    rates?.MDL?.let { rate -> ratesMap.put(Currency.getInstance("MDL"), rate) }
    rates?.MGA?.let { rate -> ratesMap.put(Currency.getInstance("MGA"), rate) }
    rates?.MKD?.let { rate -> ratesMap.put(Currency.getInstance("MKD"), rate) }
    rates?.MMK?.let { rate -> ratesMap.put(Currency.getInstance("MMK"), rate) }
    rates?.MNT?.let { rate -> ratesMap.put(Currency.getInstance("MNT"), rate) }
    rates?.MOP?.let { rate -> ratesMap.put(Currency.getInstance("MOP"), rate) }
    rates?.MRU?.let { rate -> ratesMap.put(Currency.getInstance("MRU"), rate) }
    rates?.MUR?.let { rate -> ratesMap.put(Currency.getInstance("MUR"), rate) }
    rates?.MVR?.let { rate -> ratesMap.put(Currency.getInstance("MVR"), rate) }
    rates?.MWK?.let { rate -> ratesMap.put(Currency.getInstance("MWK"), rate) }
    rates?.MXN?.let { rate -> ratesMap.put(Currency.getInstance("MXN"), rate) }
    rates?.MYR?.let { rate -> ratesMap.put(Currency.getInstance("MYR"), rate) }
    rates?.MZN?.let { rate -> ratesMap.put(Currency.getInstance("MZN"), rate) }
    rates?.NAD?.let { rate -> ratesMap.put(Currency.getInstance("NAD"), rate) }
    rates?.NGN?.let { rate -> ratesMap.put(Currency.getInstance("NGN"), rate) }
    rates?.NIO?.let { rate -> ratesMap.put(Currency.getInstance("NIO"), rate) }
    rates?.NOK?.let { rate -> ratesMap.put(Currency.getInstance("NOK"), rate) }
    rates?.NPR?.let { rate -> ratesMap.put(Currency.getInstance("NPR"), rate) }
    rates?.NZD?.let { rate -> ratesMap.put(Currency.getInstance("NZD"), rate) }
    rates?.OMR?.let { rate -> ratesMap.put(Currency.getInstance("OMR"), rate) }
    rates?.PAB?.let { rate -> ratesMap.put(Currency.getInstance("PAB"), rate) }
    rates?.PEN?.let { rate -> ratesMap.put(Currency.getInstance("PEN"), rate) }
    rates?.PGK?.let { rate -> ratesMap.put(Currency.getInstance("PGK"), rate) }
    rates?.PHP?.let { rate -> ratesMap.put(Currency.getInstance("PHP"), rate) }
    rates?.PKR?.let { rate -> ratesMap.put(Currency.getInstance("PKR"), rate) }
    rates?.PLN?.let { rate -> ratesMap.put(Currency.getInstance("PLN"), rate) }
    rates?.PYG?.let { rate -> ratesMap.put(Currency.getInstance("PYG"), rate) }
    rates?.QAR?.let { rate -> ratesMap.put(Currency.getInstance("QAR"), rate) }
    rates?.RON?.let { rate -> ratesMap.put(Currency.getInstance("RON"), rate) }
    rates?.RSD?.let { rate -> ratesMap.put(Currency.getInstance("RSD"), rate) }
    rates?.RUB?.let { rate -> ratesMap.put(Currency.getInstance("RUB"), rate) }
    rates?.RWF?.let { rate -> ratesMap.put(Currency.getInstance("RWF"), rate) }
    rates?.SAR?.let { rate -> ratesMap.put(Currency.getInstance("SAR"), rate) }
    rates?.SBD?.let { rate -> ratesMap.put(Currency.getInstance("SBD"), rate) }
    rates?.SCR?.let { rate -> ratesMap.put(Currency.getInstance("SCR"), rate) }
    rates?.SDG?.let { rate -> ratesMap.put(Currency.getInstance("SDG"), rate) }
    rates?.SEK?.let { rate -> ratesMap.put(Currency.getInstance("SEK"), rate) }
    rates?.SGD?.let { rate -> ratesMap.put(Currency.getInstance("SGD"), rate) }
    rates?.SHP?.let { rate -> ratesMap.put(Currency.getInstance("SHP"), rate) }
    rates?.SLL?.let { rate -> ratesMap.put(Currency.getInstance("SLL"), rate) }
    rates?.SOS?.let { rate -> ratesMap.put(Currency.getInstance("SOS"), rate) }
    rates?.SRD?.let { rate -> ratesMap.put(Currency.getInstance("SRD"), rate) }
    rates?.STN?.let { rate -> ratesMap.put(Currency.getInstance("STN"), rate) }
    rates?.SYP?.let { rate -> ratesMap.put(Currency.getInstance("SYP"), rate) }
    rates?.SZL?.let { rate -> ratesMap.put(Currency.getInstance("SZL"), rate) }
    rates?.THB?.let { rate -> ratesMap.put(Currency.getInstance("THB"), rate) }
    rates?.TJS?.let { rate -> ratesMap.put(Currency.getInstance("TJS"), rate) }
    rates?.TMT?.let { rate -> ratesMap.put(Currency.getInstance("TMT"), rate) }
    rates?.TND?.let { rate -> ratesMap.put(Currency.getInstance("TND"), rate) }
    rates?.TOP?.let { rate -> ratesMap.put(Currency.getInstance("TOP"), rate) }
    rates?.TRY?.let { rate -> ratesMap.put(Currency.getInstance("TRY"), rate) }
    rates?.TTD?.let { rate -> ratesMap.put(Currency.getInstance("TTD"), rate) }
    rates?.TVD?.let { rate -> ratesMap.put(Currency.getInstance("TVD"), rate) }
    rates?.TWD?.let { rate -> ratesMap.put(Currency.getInstance("TWD"), rate) }
    rates?.TZS?.let { rate -> ratesMap.put(Currency.getInstance("TZS"), rate) }
    rates?.UAH?.let { rate -> ratesMap.put(Currency.getInstance("UAH"), rate) }
    rates?.UGX?.let { rate -> ratesMap.put(Currency.getInstance("UGX"), rate) }
    rates?.USD?.let { rate -> ratesMap.put(Currency.getInstance("USD"), rate) }
    rates?.UYU?.let { rate -> ratesMap.put(Currency.getInstance("UYU"), rate) }
    rates?.UZS?.let { rate -> ratesMap.put(Currency.getInstance("UZS"), rate) }
    rates?.VES?.let { rate -> ratesMap.put(Currency.getInstance("VES"), rate) }
    rates?.VND?.let { rate -> ratesMap.put(Currency.getInstance("VND"), rate) }
    rates?.VUV?.let { rate -> ratesMap.put(Currency.getInstance("VUV"), rate) }
    rates?.WST?.let { rate -> ratesMap.put(Currency.getInstance("WST"), rate) }
    rates?.XAF?.let { rate -> ratesMap.put(Currency.getInstance("XAF"), rate) }
    rates?.XCD?.let { rate -> ratesMap.put(Currency.getInstance("XCD"), rate) }
    rates?.XDR?.let { rate -> ratesMap.put(Currency.getInstance("XDR"), rate) }
    rates?.XOF?.let { rate -> ratesMap.put(Currency.getInstance("XOF"), rate) }
    rates?.XPF?.let { rate -> ratesMap.put(Currency.getInstance("XPF"), rate) }
    rates?.YER?.let { rate -> ratesMap.put(Currency.getInstance("YER"), rate) }
    rates?.ZAR?.let { rate -> ratesMap.put(Currency.getInstance("ZAR"), rate) }
    rates?.ZMW?.let { rate -> ratesMap.put(Currency.getInstance("ZMW"), rate) }
    rates?.ZWL?.let { rate -> ratesMap.put(Currency.getInstance("ZWL"), rate) }

    return CurrencyRates(
        baseCurrency = base.orEmpty(),
        rates = ratesMap,
        requestedAtInMillis = System.currentTimeMillis()
    )
}
